# Generated by Django 4.0.2 on 2022-12-04 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_name', models.CharField(max_length=50)),
                ('emotion_type', models.CharField(max_length=50)),
                ('emotion_point', models.SmallIntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_cause', models.CharField(max_length=200)),
                ('entered_at', models.DateTimeField(verbose_name='date entered')),
                ('emotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.emotion')),
            ],
        ),
    ]
