# Generated by Django 4.0.2 on 2022-12-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='emotion_point',
            field=models.SmallIntegerField(),
        ),
    ]
